### ISSUE TITLE
Arguments mismatch for stop: "value" must be a number

### ISSUE THREAD

**Issue by jiripospisil** [laino/final-pm#8]
Hello @laino! It looks like there's an issue when downscaling an app:

```js
// conf.js
module.exports = {
  applications: [
    {
      "name": "foo",
      "run": "foo.js",
      "instances": 2,
      "ready-on": "message"
    },
  ]
};

```

```js
// foo.js
process.send('ready');
setTimeout(() => {}, 999999999);
```

```bash
final-pm -c conf.js start foo
[INFO ] [Daemon] Starting Daemon
[INFO ] [Config] foo added
[INFO ] [Action] Start 2 processes...
[INFO ] [Action] Success
```

Now change the number of `instances` in the config file to just 1 and run `scale`.

```bash
final-pm -c conf.js scale foo
[INFO ] [Config] foo{instances} updated
[INFO ] [Action] Stop 1 process...
[ERROR] [CLI] Arguments mismatch for all: Arguments mismatch for stop: "value" must be a number
```

```bash
final-pm -c conf.js show
```

![image](https://user-images.githubusercontent.com/20820/51693331-07d48300-1fff-11e9-9ae5-938e42f7e202.png)

Any ideas?

**Comment by laino** [comment]
**Fixed in 2.23.2**

It's fixed in the most recent version with this commit: https://github.com/laino/final-pm/commit/6f0b99273b9d8759c977d7a63cb7bc37f23db6a8

A restart of the daemon process is **not** required after updating.

**Severity: Low**

There's no chance of applications crashing because of this bug, since the misbehaving client (CLI)
is caught by the daemon process, which correctly reports a malformed API call.

There is also a workaround available.

**Workaround:**

On older version you can work around the issue by just manually stopping processes via ```stop```.

**Explanation:**

The CLI tries to make a call that doesn't match the server-side API at all (anymore?), hence you get the "Arguments mismatch" error. 

I'm not even sure anymore how that code got to be wrong.... It might have snuck there in another commit after I considered changing something about the API, but didn't, or vice-versa.

@jiripospisil Thanks for reporting this bug!

**Comment by jiripospisil** [comment]
Thank you for the quick fix. Works great now!

**Comment by roblav96** [comment]
@jiripospisil Great catch!

@laino I appreciate you and all the great work you've put into this amazing process manager =]
